### ISSUE TITLE
Unable to save my config

### ISSUE THREAD

**Issue by bacus99** [cconard96/jamf#116]
GLPI 10.0.2, JAMF 3.0.1

Unable to save my config in this section
![image](https://user-images.githubusercontent.com/11425241/184355787-b1244579-4f25-4a63-91c9-682862fea10d.png)

no error in logs

Causing error
  SQL: INSERT INTO `glpi_devicefirmwares` (`designation`, `manufacturers_id`, `entities_id`, `is_recursive`, `date_creation`, `date_mod`) VALUES ('433.140.2.0.0', NULL, '0', '1', '2022-08-12 07:59:57', '2022-08-12 07:59:57')
  Error: Column 'manufacturers_id' cannot be null

**Comment by cconard96** [comment]
In those dropdowns, do you see an entry like "‐--------"? If so, try switching them to that before saving. I'm not sure why it is showing "null" entries instead of empty ones which would set the IDs to 0.

**Comment by bacus99** [comment]
Same result, where can I change manually this config in DB?

![image](https://user-images.githubusercontent.com/11425241/184361596-eea2ab3e-6699-427e-a662-af46b1670b15.png)

**Comment by cconard96** [comment]
#117 Should fix this issue

**Comment by bacus99** [comment]
Still not saving
![image](https://user-images.githubusercontent.com/11425241/184413349-76d51e17-2a47-4625-8ebb-fd5e6e4ddb43.png)
****

**Comment by dbruyere** [comment]
I also have this problem even after having the fix #117 
Thank you very much for the work you do on this plugin

![after fix #117](https://user-images.githubusercontent.com/161432/186375492-63a14841-33f8-4148-be3f-69ca2943200d.jpg)

**Comment by cconard96** [comment]
Will be fixed by #126
